param(
    [string] $ManifestPath = "",
    [string] $OutHeader = ""
)
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
if (-not $ManifestPath) { $ManifestPath = Join-Path $Root "assets\ui\spritesheet-manifest.json" }
if (-not $OutHeader) { $OutHeader = Join-Path $Root "src32\include\ui_sprites.h" }
$Manifest = Get-Content -Raw -LiteralPath $ManifestPath | ConvertFrom-Json
$PngPath = Join-Path $Root ($Manifest.source -replace "/", "\")
if (-not (Test-Path -LiteralPath $PngPath)) { throw "Missing sprite sheet: $PngPath" }
Add-Type -AssemblyName System.Drawing
$Src = [System.Drawing.Bitmap]::new($PngPath)
$AlphaCut = [int]$Manifest.alphaThreshold
function Get-TrimmedPixels {
    param([int]$Rx, [int]$Ry, [int]$Rw, [int]$Rh, [int]$OutW, [int]$OutH)
    $MinX = $Rx + $Rw; $MaxX = $Rx; $MinY = $Ry + $Rh; $MaxY = $Ry
    for ($Y = $Ry; $Y -lt ($Ry + $Rh); $Y++) {
        for ($X = $Rx; $X -lt ($Rx + $Rw); $X++) {
            if ($Src.GetPixel($X, $Y).A -gt $AlphaCut) {
                if ($X -lt $MinX) { $MinX = $X }
                if ($X -gt $MaxX) { $MaxX = $X }
                if ($Y -lt $MinY) { $MinY = $Y }
                if ($Y -gt $MaxY) { $MaxY = $Y }
            }
        }
    }
    if ($MaxX -lt $MinX) { throw "Sprite region empty at $Rx,$Ry ${Rw}x$Rh" }
    $Tw = $MaxX - $MinX + 1
    $Th = $MaxY - $MinY + 1
    $Pixels = New-Object uint32[] ($OutW * $OutH)
    for ($Dy = 0; $Dy -lt $OutH; $Dy++) {
        $Sy = $MinY + [int]($Dy * $Th / $OutH)
        if ($Sy -gt $MaxY) { $Sy = $MaxY }
        for ($Dx = 0; $Dx -lt $OutW; $Dx++) {
            $Sx = $MinX + [int]($Dx * $Tw / $OutW)
            if ($Sx -gt $MaxX) { $Sx = $MaxX }
            $C = $Src.GetPixel($Sx, $Sy)
            $A = [int]$C.A
            $Argb = ([uint32]$A -shl 24) -bor ([uint32]$C.R -shl 16) -bor ([uint32]$C.G -shl 8) -bor [uint32]$C.B
            $Pixels[$Dy * $OutW + $Dx] = $Argb
        }
    }
    return @{ Pixels = $Pixels; OutW = $OutW; OutH = $OutH }
}
$Built = @()
$EnumLines = @("typedef enum {")
$TableLines = @("static const struct UiSprite ui_sprites[UI_SPRITE_COUNT] = {")
$Idx = 0
foreach ($Sp in $Manifest.sprites) {
    $R = $Sp.region
    $Data = Get-TrimmedPixels -Rx $R[0] -Ry $R[1] -Rw $R[2] -Rh $R[3] -OutW $Sp.width -OutH $Sp.height
    $Name = $Sp.name
    $EnumLines += "    UI_SPRITE_$($Name.ToUpper()) = $Idx,"
    $Hex = ($Data.Pixels | ForEach-Object { "0x{0:X8}u" -f $_ }) -join ", "
    $Built += "/* $Name from sheet region [$($R[0]),$($R[1]),$($R[2]),$($R[3])] */"
    $Built += "static const u32 ui_sprite_${Name}_pixels[] = { $Hex };"
    $TableLines += "    { $($Sp.width), $($Sp.height), ui_sprite_${Name}_pixels },"
    $Idx++
}
$EnumLines += "    UI_SPRITE_COUNT = $Idx"
$EnumLines += "} UiSpriteId;"
$TableLines += "};"
$HeaderLines = @(
    "#ifndef LEONOS_UI_SPRITES_H",
    "#define LEONOS_UI_SPRITES_H",
    "/* AUTO-GENERATED by tools/generate-ui-sprites.ps1 - DO NOT EDIT */",
    "/* Source: $($Manifest.source) */",
    "#include `"bootinfo.h`"",
    "struct UiSprite {",
    "    u16 w;",
    "    u16 h;",
    "    const u32 *argb; /* 0xAARRGGBB */",
    "};"
)
$HeaderLines += $EnumLines
$HeaderLines += $Built
$HeaderLines += $TableLines
$HeaderLines += "#endif"
$HeaderLines += ""
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutHeader, ($HeaderLines -join "`n"), $Utf8NoBom)

$ProbePath = Join-Path $Root "assets\ui\sprite-visual-probes.json"
$ProbeSprites = @{}
foreach ($Sp in $Manifest.sprites) {
    $Name = $Sp.name
    $Data = Get-TrimmedPixels -Rx $Sp.region[0] -Ry $Sp.region[1] -Rw $Sp.region[2] -Rh $Sp.region[3] -OutW $Sp.width -OutH $Sp.height
    $Cx = [int]($Sp.width / 2)
    $Cy = [int]($Sp.height / 2)
    $Px = $Data.Pixels[$Cy * $Sp.width + $Cx]
    $A = ($Px -shr 24) -band 0xFF
    $Kr = ($Px -shr 16) -band 0xFF
    $Kg = ($Px -shr 8) -band 0xFF
    $Kb = $Px -band 0xFF
    $Kernel = ("0x{0:X8}" -f (($A -shl 24) -bor ($Kr -shl 16) -bor ($Kg -shl 8) -bor $Kb))
    $ProbeSprites[$Name] = @{ kernelColor = $Kernel; centerArgb = ("0x{0:X8}" -f $Px) }
}
$ProbeDoc = @{
    source = $Manifest.source
    manifest = "assets/ui/spritesheet-manifest.json"
    sprites = $ProbeSprites
} | ConvertTo-Json -Depth 4
[System.IO.File]::WriteAllText($ProbePath, $ProbeDoc, $Utf8NoBom)

$Src.Dispose()
Write-Host "Generated $OutHeader ($Idx sprites) from $PngPath"
Write-Host "Wrote $ProbePath"
