param(
    [string] $VendorDir = "ports\netsurf\vendor",
    [string[]] $Libraries = @(
        "libwapcaplet",
        "libparserutils",
        "libhubbub",
        "libcss",
        "libdom",
        "libnsbmp",
        "libnsgif",
        "libsvgtiny",
        "libnsutils",
        "netsurf-monkey"
    ),
    [string] $StartUrl = "https://www.google.com/?igu=1&hl=en&gbv=1",
    [ValidateRange(0, 100000)]
    [int] $SettlePolls = 64,
    [switch] $Interactive,
    [switch] $NonInteractive,
    [switch] $EnableJavaScriptByDefault,
    [switch] $NoJavaScript,
    [switch] $UseQuickJsCore
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $Root "tools\toolchain.ps1")

$VendorPath = Join-Path $Root $VendorDir
$Toolchain = Get-LeonOsI386Toolchain
$Nasm = Get-LeonOsNasmPath
$Out = Join-Path $Root "dist32\netsurf-probe"
$LibcInc = Join-Path $Root "ports\netsurf\leonos_libc\include"
$LibcSrc = Join-Path $Root "ports\netsurf\leonos_libc\src\leostd.c"
$LibcSetjmpSrc = Join-Path $Root "ports\netsurf\leonos_libc\src\setjmp_i386.asm"
$LeoFetchSrc = Join-Path $Root "ports\netsurf\leonos_libc\src\leonos_fetch.c"
$LeoStbImageSrc = Join-Path $Root "ports\netsurf\leonos_libc\src\leonos_stb_image.c"
$Leo1MainSrc = Join-Path $Root "ports\netsurf\leonos_libc\src\netsurf_leo1_main.c"
$Src32Include = Join-Path $Root "src32\include"
$QuickJsVersion = "2026-06-04"
$QuickJsSource = Join-Path $Root "ports\quickjs\vendor\quickjs-$QuickJsVersion"
$QuickJsBackendSrc = Join-Path $Root "ports\netsurf\leonos_frontend\leonos_quickjs_backend.c"
New-Item -ItemType Directory -Path $Out -Force | Out-Null

if ([string]::IsNullOrWhiteSpace($StartUrl) -or
    -not $StartUrl.StartsWith("https://", [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "StartUrl must be a non-empty https:// URL."
}
if ($Interactive -and $NonInteractive) {
    throw "Interactive and NonInteractive cannot be used together."
}
if ($NoJavaScript -and $UseQuickJsCore) {
    throw "NoJavaScript and UseQuickJsCore cannot be used together."
}
$InteractiveMode = $Interactive.IsPresent -or -not $NonInteractive.IsPresent

function ConvertTo-CStringLiteral {
    param([string] $Text)

    $Sb = [System.Text.StringBuilder]::new()
    foreach ($Ch in $Text.ToCharArray()) {
        if ($Ch -eq '\') {
            [void] $Sb.Append("\\")
        } elseif ($Ch -eq '"') {
            [void] $Sb.Append('\"')
        } elseif ($Ch -eq "`n") {
            [void] $Sb.Append("\n")
        } elseif ($Ch -eq "`r") {
            [void] $Sb.Append("\r")
        } elseif ([int][char]$Ch -lt 32 -or [int][char]$Ch -gt 126) {
            [void] $Sb.Append(("\x{0:X2}" -f [int][char]$Ch))
        } else {
            [void] $Sb.Append($Ch)
        }
    }
    return $Sb.ToString()
}

$NetSurfConfigHeader = Join-Path $Out "leonos_netsurf_config.h"
[System.IO.File]::WriteAllLines($NetSurfConfigHeader, @(
    "/* Generated by ports/netsurf/build-leonos-probe.ps1 */",
    "#ifndef LEONOS_NETSURF_CONFIG_H",
    "#define LEONOS_NETSURF_CONFIG_H",
    "#define LEONOS_NETSURF_START_URL `"$((ConvertTo-CStringLiteral $StartUrl))`"",
    "#define LEONOS_NETSURF_SETTLE_POLLS $($SettlePolls)u",
    "#define LEONOS_NETSURF_INTERACTIVE $([int] $InteractiveMode)",
    "#define LEONOS_NETSURF_HAS_JAVASCRIPT $([int] (-not $NoJavaScript.IsPresent))",
    "#define LEONOS_NETSURF_DEFAULT_JAVASCRIPT $([int] ($EnableJavaScriptByDefault.IsPresent -and -not $NoJavaScript.IsPresent))",
    "#endif"
), [System.Text.Encoding]::ASCII)

function Sync-Leo1ImageSize {
    param([byte[]] $Bytes)
    if ($Bytes.Length -lt 20) {
        throw "LEO1 image is too small to patch."
    }
    $ImageSize = $Bytes.Length
    $Bytes[12] = [byte] ($ImageSize -band 0xFF)
    $Bytes[13] = [byte] (($ImageSize -shr 8) -band 0xFF)
    $Bytes[14] = [byte] (($ImageSize -shr 16) -band 0xFF)
    $Bytes[15] = [byte] (($ImageSize -shr 24) -band 0xFF)
    return $Bytes
}

function Ensure-LibParserUtilsGeneratedFiles {
    $ParserUtilsRoot = Join-Path $VendorPath "libparserutils"
    $AliasesInc = Join-Path $ParserUtilsRoot "src\charset\aliases.inc"
    if (Test-Path -LiteralPath $AliasesInc) {
        return
    }

    $AliasesFile = Join-Path $ParserUtilsRoot "build\Aliases"
    if (-not (Test-Path -LiteralPath $AliasesFile)) {
        throw "libparserutils aliases source missing at $AliasesFile."
    }

    function ConvertTo-AliasKey {
        param([string] $Value)
        return (($Value.ToLowerInvariant()) -replace '[^a-z0-9]', '')
    }

    function Escape-CString {
        param([string] $Value)
        return (($Value -replace '\\', '\\') -replace '"', '\"')
    }

    $Rows = @()
    foreach ($Line in Get-Content -LiteralPath $AliasesFile) {
        $Trimmed = $Line.Trim()
        if ($Trimmed.Length -eq 0 -or $Trimmed.StartsWith("#")) {
            continue
        }
        $Parts = $Trimmed -split '\s+'
        if ($Parts.Count -lt 2) {
            continue
        }
        $Rows += [pscustomobject] @{
            Canon = $Parts[0]
            Mib = $Parts[1]
            Aliases = @($Parts | Select-Object -Skip 2)
        }
    }

    $Rows = @($Rows | Sort-Object Canon)
    $AliasMap = @{}
    $UnicodeExpr = [System.Collections.Generic.List[string]]::new()
    $Sb = [System.Text.StringBuilder]::new()
    [void] $Sb.AppendLine("/*")
    [void] $Sb.AppendLine(" * Generated by ports/netsurf/build-leonos-probe.ps1")
    [void] $Sb.AppendLine(" */")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("static parserutils_charset_aliases_canon canonical_charset_names[] = {")
    for ($Index = 0; $Index -lt $Rows.Count; $Index += 1) {
        $Row = $Rows[$Index]
        [void] $Sb.AppendLine(("`t{{ {0}, {1}, `"{2}`" }}," -f $Row.Mib, $Row.Canon.Length, (Escape-CString $Row.Canon)))
        if ($Row.Canon -match '^ISO-10646-UCS-[24]$' -or
            $Row.Canon -match '^UTF-16' -or
            $Row.Canon -match '^UTF-8$' -or
            $Row.Canon -match '^UTF-32') {
            [void] $UnicodeExpr.Add(("((x) == {0})" -f $Row.Mib))
        }
        $AliasMap[(ConvertTo-AliasKey $Row.Canon)] = $Index
        foreach ($Alias in $Row.Aliases) {
            $AliasMap[(ConvertTo-AliasKey $Alias)] = $Index
        }
    }
    [void] $Sb.AppendLine("};")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine(("static const uint16_t charset_aliases_canon_count = {0};" -f $Rows.Count))
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("typedef struct {")
    [void] $Sb.AppendLine("`tuint16_t name_len;")
    [void] $Sb.AppendLine("`tconst char *name;")
    [void] $Sb.AppendLine("`tparserutils_charset_aliases_canon *canon;")
    [void] $Sb.AppendLine("} parserutils_charset_aliases_alias;")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("static parserutils_charset_aliases_alias charset_aliases[] = {")
    foreach ($AliasKey in ($AliasMap.Keys | Sort-Object)) {
        [void] $Sb.AppendLine(("`t{{ {0}, `"{1}`", &canonical_charset_names[{2}] }}," -f $AliasKey.Length, $AliasKey, $AliasMap[$AliasKey]))
    }
    [void] $Sb.AppendLine("};")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine(("static const uint16_t charset_aliases_count = {0};" -f $AliasMap.Count))
    [void] $Sb.AppendLine()
    $Unicode = if ($UnicodeExpr.Count -gt 0) { [string]::Join(" || ", $UnicodeExpr) } else { "0" }
    [void] $Sb.AppendLine(("#define MIBENUM_IS_UNICODE(x) ({0})" -f $Unicode))

    [System.IO.File]::WriteAllText($AliasesInc, $Sb.ToString(), [System.Text.Encoding]::ASCII)
    if (-not (Test-Path -LiteralPath $AliasesInc)) {
        throw "libparserutils aliases.inc was not generated."
    }
}

function Ensure-HubbubGeneratedFiles {
    $HubbubRoot = Join-Path $VendorPath "libhubbub"
    $EntitiesInc = Join-Path $HubbubRoot "src\tokeniser\entities.inc"
    $ElementTypeInc = Join-Path $HubbubRoot "src\treebuilder\autogenerated-element-type.c"

    $EntitiesFile = Join-Path $HubbubRoot "build\Entities"
    if (-not (Test-Path -LiteralPath $EntitiesFile)) {
        throw "libhubbub entities source missing at $EntitiesFile."
    }

    $Entities = @{}
    foreach ($Line in Get-Content -LiteralPath $EntitiesFile) {
        $Trimmed = $Line.Trim()
        if ($Trimmed.Length -eq 0 -or $Trimmed.StartsWith("#")) {
            continue
        }
        $Parts = $Trimmed -split '\s+'
        if ($Parts.Count -lt 2) {
            continue
        }
        $Entities[$Parts[0]] = $Parts[1]
    }

    $script:HubbubEntityHeapIndex = 0
    $script:HubbubEntityNodes = [System.Collections.Generic.List[object]]::new()

    function New-HubbubEntityNode {
        param([string] $Pivot)

        $Node = [pscustomobject] @{
            Pivot = $Pivot
            HeapIndex = $script:HubbubEntityHeapIndex
            Lt = $null
            Eq = $null
            Gt = $null
            Value = $null
        }
        $script:HubbubEntityHeapIndex += 1
        [void] $script:HubbubEntityNodes.Add($Node)
        return $Node
    }

    function Add-HubbubEntityNode {
        param(
            $Parent,
            [string] $Key,
            [string] $Code
        )

        if ($Key.Length -eq 0) {
            $Pivot = ""
            $Tail = ""
        } elseif ($Key.Length -eq 1) {
            $Pivot = $Key
            $Tail = ""
        } else {
            $Pivot = $Key.Substring(0, 1)
            $Tail = $Key.Substring(1)
        }

        if ($null -eq $Parent) {
            $Parent = New-HubbubEntityNode -Pivot $Pivot
        }

        $Compare = [string]::CompareOrdinal($Pivot, [string] $Parent.Pivot)
        if ($Compare -lt 0) {
            $Parent.Lt = Add-HubbubEntityNode -Parent $Parent.Lt -Key $Key -Code $Code
        } elseif ($Compare -eq 0) {
            if ($Pivot -eq "") {
                $Parent.Value = $Code
            } elseif ($Tail.Length -eq 0) {
                $Parent.Value = $Code
                $Parent.Eq = Add-HubbubEntityNode -Parent $Parent.Eq -Key $Tail -Code $Code
            } else {
                $Parent.Eq = Add-HubbubEntityNode -Parent $Parent.Eq -Key $Tail -Code $Code
            }
        } else {
            $Parent.Gt = Add-HubbubEntityNode -Parent $Parent.Gt -Key $Key -Code $Code
        }

        return $Parent
    }

    $Trie = $null
    foreach ($Key in ($Entities.Keys | Sort-Object)) {
        $Trie = Add-HubbubEntityNode -Parent $Trie -Key $Key -Code $Entities[$Key]
    }

    $Sb = [System.Text.StringBuilder]::new()
    [void] $Sb.AppendLine("/*")
    [void] $Sb.AppendLine(" * This file is part of Hubbub.")
    [void] $Sb.AppendLine(" * Generated by ports/netsurf/build-leonos-probe.ps1")
    [void] $Sb.AppendLine(" */")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("static hubbub_entity_node dict[] = {")
    foreach ($Node in $script:HubbubEntityNodes) {
        $Split = if ($Node.Pivot -eq "") { 0 } else { [int] [char] $Node.Pivot[0] }
        $Lt = if ($null -eq $Node.Lt) { -1 } else { $Node.Lt.HeapIndex }
        $Eq = if ($null -eq $Node.Eq) { -1 } else { $Node.Eq.HeapIndex }
        $Gt = if ($null -eq $Node.Gt) { -1 } else { $Node.Gt.HeapIndex }
        $Value = if ($null -eq $Node.Value) { "0" } else { $Node.Value }
        [void] $Sb.AppendLine(("`t{{ {0}, {1}, {2}, {3}, {4} }}," -f $Split, $Lt, $Eq, $Gt, $Value))
    }
    [void] $Sb.AppendLine("};")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine(("static int32_t dict_root = {0};" -f $Trie.HeapIndex))

    [System.IO.File]::WriteAllText($EntitiesInc, $Sb.ToString(), [System.Text.Encoding]::ASCII)
    if (-not (Test-Path -LiteralPath $EntitiesInc)) {
        throw "libhubbub entities.inc was not generated."
    }

    $ElementGperf = Join-Path $HubbubRoot "src\treebuilder\element-type.gperf"
    if (-not (Test-Path -LiteralPath $ElementGperf)) {
        throw "libhubbub element type source missing at $ElementGperf."
    }

    function Escape-HubbubCString {
        param([string] $Value)
        return (($Value -replace '\\', '\\') -replace '"', '\"')
    }

    $Rows = @()
    $InWords = $false
    foreach ($Line in Get-Content -LiteralPath $ElementGperf) {
        $Trimmed = $Line.Trim()
        if ($Trimmed -eq "%%") {
            $InWords = -not $InWords
            continue
        }
        if (-not $InWords -or $Trimmed.Length -eq 0 -or $Trimmed.StartsWith("#")) {
            continue
        }
        $Parts = $Trimmed -split ',', 2
        if ($Parts.Count -ne 2) {
            continue
        }
        $Rows += [pscustomobject] @{
            Name = $Parts[0].Trim()
            Type = $Parts[1].Trim()
        }
    }
    if ($Rows.Count -eq 0) {
        throw "libhubbub element type generator found no rows."
    }

    $ElementSb = [System.Text.StringBuilder]::new()
    [void] $ElementSb.AppendLine("/*")
    [void] $ElementSb.AppendLine(" * This file is part of Hubbub.")
    [void] $ElementSb.AppendLine(" * Generated by ports/netsurf/build-leonos-probe.ps1")
    [void] $ElementSb.AppendLine(" */")
    [void] $ElementSb.AppendLine()
    [void] $ElementSb.AppendLine("#include <string.h>")
    [void] $ElementSb.AppendLine("#include <strings.h>")
    [void] $ElementSb.AppendLine()
    [void] $ElementSb.AppendLine("static const struct element_type_map wordlist[] = {")
    foreach ($Row in $Rows) {
        [void] $ElementSb.AppendLine(("`t{{ `"{0}`", {1} }}," -f (Escape-HubbubCString $Row.Name), $Row.Type))
    }
    [void] $ElementSb.AppendLine("};")
    [void] $ElementSb.AppendLine()
    [void] $ElementSb.AppendLine("static const struct element_type_map *")
    [void] $ElementSb.AppendLine("hubbub_element_type_generated_lookup(const char *str, size_t len)")
    [void] $ElementSb.AppendLine("{")
    [void] $ElementSb.AppendLine("`tfor (size_t i = 0; i < sizeof(wordlist) / sizeof(wordlist[0]); i += 1) {")
    [void] $ElementSb.AppendLine("`t`tif (strlen(wordlist[i].name) == len &&")
    [void] $ElementSb.AppendLine("`t`t`tstrncasecmp(wordlist[i].name, str, len) == 0) {")
    [void] $ElementSb.AppendLine("`t`t`treturn &wordlist[i];")
    [void] $ElementSb.AppendLine("`t`t}")
    [void] $ElementSb.AppendLine("`t}")
    [void] $ElementSb.AppendLine("`treturn NULL;")
    [void] $ElementSb.AppendLine("}")

    [System.IO.File]::WriteAllText($ElementTypeInc, $ElementSb.ToString(), [System.Text.Encoding]::ASCII)
    if (-not (Test-Path -LiteralPath $ElementTypeInc)) {
        throw "libhubbub autogenerated-element-type.c was not generated."
    }
}

function Ensure-LibDomInstalledHeaders {
    $DomRoot = Join-Path $VendorPath "libdom"
    $Bindings = @(
        [pscustomobject] @{
            Source = Join-Path $DomRoot "bindings\xml"
            Target = Join-Path $DomRoot "include\dom\bindings\xml"
            Files = @("xmlparser.h", "xmlerror.h")
        },
        [pscustomobject] @{
            Source = Join-Path $DomRoot "bindings\hubbub"
            Target = Join-Path $DomRoot "include\dom\bindings\hubbub"
            Files = @("parser.h", "errors.h")
        }
    )

    foreach ($Binding in $Bindings) {
        if (-not (Test-Path -LiteralPath $Binding.Source)) {
            throw "libdom binding source missing at $($Binding.Source)."
        }
        New-Item -ItemType Directory -Path $Binding.Target -Force | Out-Null
        foreach ($File in $Binding.Files) {
            $SrcFile = Join-Path $Binding.Source $File
            $DstFile = Join-Path $Binding.Target $File
            if (-not (Test-Path -LiteralPath $SrcFile)) {
                throw "libdom binding header missing at $SrcFile."
            }
            Copy-Item -LiteralPath $SrcFile -Destination $DstFile -Force
        }
    }
}

function Ensure-LibSvgTinyGeneratedFiles {
    $SvgRoot = Join-Path $VendorPath "libsvgtiny"
    $ColorsGperf = Join-Path $SvgRoot "src\colors.gperf"
    $ColorsInc = Join-Path $SvgRoot "src\autogenerated_colors.c"
    if (-not (Test-Path -LiteralPath $ColorsGperf)) {
        throw "libsvgtiny color source missing at $ColorsGperf."
    }

    function Escape-SvgCString {
        param([string] $Value)
        return (($Value -replace '\\', '\\') -replace '"', '\"')
    }

    $Rows = @()
    $InWords = $false
    foreach ($Line in Get-Content -LiteralPath $ColorsGperf) {
        $Trimmed = $Line.Trim()
        if ($Trimmed -eq "%%") {
            $InWords = -not $InWords
            continue
        }
        if (-not $InWords -or $Trimmed.Length -eq 0 -or $Trimmed.StartsWith("#")) {
            continue
        }
        $Parts = $Trimmed -split ',', 2
        if ($Parts.Count -ne 2) {
            continue
        }
        $Rows += [pscustomobject] @{
            Name = $Parts[0].Trim()
            Color = $Parts[1].Trim()
        }
    }
    if ($Rows.Count -eq 0) {
        throw "libsvgtiny color generator found no rows."
    }

    $Sb = [System.Text.StringBuilder]::new()
    [void] $Sb.AppendLine("/*")
    [void] $Sb.AppendLine(" * This file is part of Libsvgtiny.")
    [void] $Sb.AppendLine(" * Generated by ports/netsurf/build-leonos-probe.ps1")
    [void] $Sb.AppendLine(" */")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("#include <string.h>")
    [void] $Sb.AppendLine("#include <strings.h>")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("static const struct svgtiny_named_color wordlist[] = {")
    foreach ($Row in $Rows) {
        [void] $Sb.AppendLine(("`t{{ `"{0}`", {1} }}," -f (Escape-SvgCString $Row.Name), $Row.Color))
    }
    [void] $Sb.AppendLine("};")
    [void] $Sb.AppendLine()
    [void] $Sb.AppendLine("static const struct svgtiny_named_color *")
    [void] $Sb.AppendLine("svgtiny_color_lookup(const char *str, size_t len)")
    [void] $Sb.AppendLine("{")
    [void] $Sb.AppendLine("`tfor (size_t i = 0; i < sizeof(wordlist) / sizeof(wordlist[0]); i += 1) {")
    [void] $Sb.AppendLine("`t`tif (strlen(wordlist[i].name) == len &&")
    [void] $Sb.AppendLine("`t`t`tstrncasecmp(wordlist[i].name, str, len) == 0) {")
    [void] $Sb.AppendLine("`t`t`treturn &wordlist[i];")
    [void] $Sb.AppendLine("`t`t}")
    [void] $Sb.AppendLine("`t}")
    [void] $Sb.AppendLine("`treturn NULL;")
    [void] $Sb.AppendLine("}")

    [System.IO.File]::WriteAllText($ColorsInc, $Sb.ToString(), [System.Text.Encoding]::ASCII)
    if (-not (Test-Path -LiteralPath $ColorsInc)) {
        throw "libsvgtiny autogenerated_colors.c was not generated."
    }
}

function Get-LeonOsHostCCompiler {
    $Compiler = Find-LeonOsCommand `
        -Names @("clang.exe", "clang", "gcc.exe", "gcc") `
        -Candidates @(
            (Join-Path $LeonOsLocalLlvm "clang.exe"),
            (Join-Path $LeonOsLocalLlvm "gcc.exe")
        )

    if (-not $Compiler) {
        throw "A host C compiler was not found for NetSurf generated build tools."
    }

    return $Compiler
}

function Ensure-LibCssGeneratedFiles {
    $CssRoot = Join-Path $VendorPath "libcss"
    $PropertiesDir = Join-Path $CssRoot "src\parse\properties"
    $PropertiesGen = Join-Path $PropertiesDir "properties.gen"
    $GeneratorSrc = Join-Path $PropertiesDir "css_property_parser_gen.c"
    if (-not (Test-Path -LiteralPath $PropertiesGen)) {
        throw "libcss properties.gen missing at $PropertiesGen."
    }
    if (-not (Test-Path -LiteralPath $GeneratorSrc)) {
        throw "libcss property generator source missing at $GeneratorSrc."
    }

    $HostDir = Join-Path $Out "host"
    New-Item -ItemType Directory -Path $HostDir -Force | Out-Null
    $GeneratorExe = Join-Path $HostDir "css-gen-parser.exe"
    $HostCc = Get-LeonOsHostCCompiler
    & $HostCc $GeneratorSrc "-O2" "-o" $GeneratorExe
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $GeneratorExe)) {
        throw "Failed to build libcss host property generator."
    }

    foreach ($Line in Get-Content -LiteralPath $PropertiesGen) {
        $Trimmed = $Line.Trim()
        if ($Trimmed.Length -eq 0 -or $Trimmed.StartsWith("#")) {
            continue
        }
        $Colon = $Trimmed.IndexOf(":")
        if ($Colon -le 0) {
            continue
        }
        $PropertyName = $Trimmed.Substring(0, $Colon)
        $OutFile = Join-Path $PropertiesDir ("autogenerated_{0}.c" -f $PropertyName)
        & $GeneratorExe "-o" $OutFile $Trimmed
        if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $OutFile)) {
            throw "Failed to generate libcss property parser $PropertyName."
        }
    }
}

function Ensure-NetSurfGeneratedFiles {
    $GeneratedRoot = Join-Path $Out "netsurf-generated"
    New-Item -ItemType Directory -Path $GeneratedRoot -Force | Out-Null

    $Testament = Join-Path $GeneratedRoot "testament.h"
    $Text = @(
        "#ifndef NETSURF_TESTAMENT_H_",
        "#define NETSURF_TESTAMENT_H_",
        "#define WT_BRANCHPATH ""LeonOS-port""",
        "#define WT_REVID ""leonos-probe""",
        "#define WT_COMPILEDATE ""2026-06-05""",
        "#define WT_HOSTNAME ""LeonOS-build""",
        "#define WT_ROOT ""/leonos/ports/netsurf""",
        "#define WT_MODIFIED 0",
        "#define WT_MODIFICATIONS {}",
        "#define WT_NO_GIT",
        "#define USERNAME ""leonos""",
        "#define GECOS ""LeonOS""",
        "#endif"
    )
    [System.IO.File]::WriteAllLines($Testament, $Text, [System.Text.Encoding]::ASCII)
}

function Write-NetSurfCByteInclude {
    param(
        [string] $InputPath,
        [string] $OutputPath,
        [string] $SymbolName
    )

    $Bytes = [System.IO.File]::ReadAllBytes($InputPath)
    $Sb = [System.Text.StringBuilder]::new()
    [void] $Sb.AppendLine("/* Generated by ports/netsurf/build-leonos-probe.ps1 */")
    [void] $Sb.AppendLine(("static const unsigned char {0}[] = {{" -f $SymbolName))
    for ($Offset = 0; $Offset -lt $Bytes.Length; $Offset += 12) {
        $Chunk = @()
        for ($Index = 0; $Index -lt 12 -and ($Offset + $Index) -lt $Bytes.Length; $Index += 1) {
            $Chunk += ("0x{0:x2}" -f $Bytes[$Offset + $Index])
        }
        [void] $Sb.AppendLine(("    {0}," -f ([string]::Join(", ", $Chunk))))
    }
    [void] $Sb.AppendLine("};")
    [void] $Sb.AppendLine(("static const unsigned int {0}_len = {1};" -f $SymbolName, $Bytes.Length))
    [System.IO.File]::WriteAllText($OutputPath, $Sb.ToString(), [System.Text.Encoding]::ASCII)
}

function Ensure-NetSurfDuktapeGeneratedFiles {
    $NetSurfRoot = Join-Path $VendorPath "netsurf"
    $GeneratedRoot = Join-Path $Out "netsurf-generated"
    $DuktapeOut = Join-Path $GeneratedRoot "duktape"
    $Nsgenbind = Join-Path $Root "dist32\nsgenbind-build\nsgenbind.exe"

    if (-not (Test-Path -LiteralPath $Nsgenbind)) {
        & (Join-Path $PSScriptRoot "build-nsgenbind.ps1") | Write-Host
    }
    if (-not (Test-Path -LiteralPath $Nsgenbind)) {
        throw "nsgenbind.exe was not built at $Nsgenbind."
    }

    Remove-Item -LiteralPath $DuktapeOut -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Path $DuktapeOut -Force | Out-Null

    Push-Location (Join-Path $NetSurfRoot "content\handlers\javascript\duktape")
    try {
        & $Nsgenbind -D -I "..\WebIDL" "netsurf.bnd" $DuktapeOut *> (Join-Path $DuktapeOut "nsgenbind.log")
        if ($LASTEXITCODE -ne 0) {
            throw "nsgenbind failed while generating Duktape bindings. See $DuktapeOut\nsgenbind.log."
        }
    } finally {
        Pop-Location
    }

    foreach ($Required in @("binding.c", "binding.h", "private.h", "prototype.h", "Makefile")) {
        $RequiredPath = Join-Path $DuktapeOut $Required
        if (-not (Test-Path -LiteralPath $RequiredPath)) {
            throw "nsgenbind did not generate $RequiredPath."
        }
    }

    Write-NetSurfCByteInclude `
        -InputPath (Join-Path $NetSurfRoot "content\handlers\javascript\duktape\generics.js") `
        -OutputPath (Join-Path $DuktapeOut "generics.js.inc") `
        -SymbolName "generics_js"
    Write-NetSurfCByteInclude `
        -InputPath (Join-Path $NetSurfRoot "content\handlers\javascript\duktape\polyfill.js") `
        -OutputPath (Join-Path $DuktapeOut "polyfill.js.inc") `
        -SymbolName "polyfill_js"

    Write-Host ("LeonOS NetSurf probe: generated Duktape bindings in {0}" -f $DuktapeOut)
}

function Ensure-NetSurfLeonOsSourcePatches {
    $NetSurfRoot = Join-Path $VendorPath "netsurf"
    $FetchSource = Join-Path $NetSurfRoot "content\fetch.c"
    $PlotSource = Join-Path $NetSurfRoot "frontends\monkey\plot.c"
    $BrowserSource = Join-Path $NetSurfRoot "frontends\monkey\browser.c"
    $BrowserHeader = Join-Path $NetSurfRoot "frontends\monkey\browser.h"

    if (-not (Test-Path -LiteralPath $FetchSource)) {
        throw "NetSurf fetch source missing at $FetchSource."
    }
    if (-not (Test-Path -LiteralPath $PlotSource)) {
        throw "NetSurf monkey plot source missing at $PlotSource."
    }
    if (-not (Test-Path -LiteralPath $BrowserSource)) {
        throw "NetSurf monkey browser source missing at $BrowserSource."
    }
    if (-not (Test-Path -LiteralPath $BrowserHeader)) {
        throw "NetSurf monkey browser header missing at $BrowserHeader."
    }

    $FetchText = [System.IO.File]::ReadAllText($FetchSource) -replace "`r`n", "`n"
    if ($FetchText -notmatch 'leonos_fetcher_register') {
        $OldInclude = '#include "content/urldb.h"'
        $NewInclude = @'
#include "content/urldb.h"

#ifdef WITH_LEONOS_FETCHER
nserror leonos_fetcher_register(void);
#endif
'@
        $NewInclude = $NewInclude -replace "`r`n", "`n"
        if (-not $FetchText.Contains($OldInclude)) {
            throw "Could not patch NetSurf fetcher prototype hook."
        }
        $FetchText = $FetchText.Replace($OldInclude, $NewInclude)

        $OldRegister = @'
	ret = fetch_javascript_register();
	if (ret != NSERROR_OK) {
		return ret;
	}

	return ret;
'@
        $OldRegister = $OldRegister -replace "`r`n", "`n"
        $NewRegister = @'
	ret = fetch_javascript_register();
	if (ret != NSERROR_OK) {
		return ret;
	}

#ifdef WITH_LEONOS_FETCHER
	ret = leonos_fetcher_register();
#endif

	return ret;
'@
        $NewRegister = $NewRegister -replace "`r`n", "`n"
        if (-not $FetchText.Contains($OldRegister)) {
            throw "Could not patch NetSurf fetcher registration hook."
        }
        $FetchText = $FetchText.Replace($OldRegister, $NewRegister)
        [System.IO.File]::WriteAllText($FetchSource, $FetchText, [System.Text.Encoding]::ASCII)
    }

    $PlotText = [System.IO.File]::ReadAllText($PlotSource) -replace "`r`n", "`n"
    if ($PlotText -notmatch 'LEN %u STR') {
        $OldPlotLine = "`tmoutf(MOUT_PLOT, `"TEXT X %d Y %d STR %.*s`", x, y, (int)length, text);"
        $NewPlotBlock = @'
#ifdef WITH_LEONOS_FETCHER
	size_t capped = length;
	char preview[49];
	size_t i;

	if (capped > 48) {
		capped = 48;
	}
	for (i = 0; i < capped; i++) {
		char ch = text[i];
		preview[i] = (ch == '\r' || ch == '\n' || ch == '\t') ? ' ' : ch;
	}
	preview[capped] = 0;
	moutf(MOUT_PLOT, "TEXT X %d Y %d LEN %u STR %s", x, y,
	      (unsigned int)length, preview);
#else
	moutf(MOUT_PLOT, "TEXT X %d Y %d STR %.*s", x, y, (int)length, text);
#endif
'@
        $NewPlotBlock = $NewPlotBlock -replace "`r`n", "`n"
        if (-not $PlotText.Contains($OldPlotLine)) {
            throw "Could not patch NetSurf monkey plot text output."
        }
        $PlotText = $PlotText.Replace($OldPlotLine, $NewPlotBlock)
        [System.IO.File]::WriteAllText($PlotSource, $PlotText, [System.Text.Encoding]::ASCII)
    }

    $BrowserHeaderText = [System.IO.File]::ReadAllText($BrowserHeader) -replace "`r`n", "`n"
    if ($BrowserHeaderText -notmatch 'redraw_scheduled') {
        $OldHeaderBlock = @'
	int width, height;
	int scrollx, scrolly;
	char current_url[512];
'@
        $OldHeaderBlock = $OldHeaderBlock -replace "`r`n", "`n"
        $NewHeaderBlock = @'
	int width, height;
	int scrollx, scrolly;
	char current_url[512];
	int redraw_scheduled;
	int redraw_again;
	int in_redraw;
'@
        $NewHeaderBlock = $NewHeaderBlock -replace "`r`n", "`n"
        if (-not $BrowserHeaderText.Contains($OldHeaderBlock)) {
            throw "Could not patch NetSurf monkey browser redraw state fields."
        }
        $BrowserHeaderText = $BrowserHeaderText.Replace($OldHeaderBlock, $NewHeaderBlock)
        [System.IO.File]::WriteAllText($BrowserHeader, $BrowserHeaderText, [System.Text.Encoding]::ASCII)
    }

    $BrowserText = [System.IO.File]::ReadAllText($BrowserSource) -replace "`r`n", "`n"
    if ($BrowserText -notmatch '#include "monkey/schedule.h"') {
        $OldInclude = '#include "monkey/plot.h"'
        $NewInclude = @'
#include "monkey/plot.h"
#include "monkey/schedule.h"
'@
        $NewInclude = $NewInclude -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldInclude)) {
            throw "Could not patch NetSurf monkey browser schedule include."
        }
        $BrowserText = $BrowserText.Replace($OldInclude, $NewInclude.TrimEnd())
    }
    if ($BrowserText -notmatch '#include "utils/nsoption.h"') {
        $OldInclude = '#include "utils/messages.h"'
        $NewInclude = @'
#include "utils/messages.h"
#include "utils/nsoption.h"
'@
        $NewInclude = $NewInclude -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldInclude)) {
            throw "Could not patch NetSurf monkey browser option include."
        }
        $BrowserText = $BrowserText.Replace($OldInclude, $NewInclude.TrimEnd())
    }
    if ($BrowserText -notmatch 'monkey_window_request_redraw') {
        $OldForward = @'
static void
monkey_window_redraw_content(struct gui_window *gw, const struct rect *clip_in);
'@
        $OldForward = $OldForward -replace "`r`n", "`n"
        $NewForward = @'
static void
monkey_window_redraw_content(struct gui_window *gw, const struct rect *clip_in);
static void
monkey_window_redraw_scheduled(void *p);

static void
monkey_window_request_redraw(struct gui_window *gw)
{
	if (gw == NULL) {
		return;
	}
	if (gw->in_redraw) {
		gw->redraw_again = 1;
		return;
	}
	if (gw->redraw_scheduled) {
		return;
	}
	gw->redraw_scheduled = 1;
	(void)monkey_schedule(0, monkey_window_redraw_scheduled, gw);
}

static void
monkey_window_redraw_scheduled(void *p)
{
	struct gui_window *gw = p;
	if (gw == NULL) {
		return;
	}
	gw->redraw_scheduled = 0;
	if (gw->in_redraw) {
		monkey_window_request_redraw(gw);
		return;
	}
	monkey_window_redraw_content(gw, NULL);
}
'@
        $NewForward = $NewForward -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldForward)) {
            throw "Could not patch NetSurf monkey browser redraw scheduler."
        }
        $BrowserText = $BrowserText.Replace($OldForward, $NewForward)
    }
    if ($BrowserText -notmatch 'monkey_window_redraw_scheduled, g') {
        $OldDestroy = @'
	moutf(MOUT_WINDOW, "DESTROY WIN %u", g->win_num);
	RING_REMOVE(gw_ring, g);
'@
        $OldDestroy = $OldDestroy -replace "`r`n", "`n"
        $NewDestroy = @'
	moutf(MOUT_WINDOW, "DESTROY WIN %u", g->win_num);
	(void)monkey_schedule(-1, monkey_window_redraw_scheduled, g);
	RING_REMOVE(gw_ring, g);
'@
        $NewDestroy = $NewDestroy -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldDestroy)) {
            throw "Could not patch NetSurf monkey browser destroy redraw cleanup."
        }
        $BrowserText = $BrowserText.Replace($OldDestroy, $NewDestroy)
    }
    if ($BrowserText -notmatch 'monkey_window_request_redraw\(gw\);\n\treturn NSERROR_OK;') {
        $OldInvalidateReturn = @'

	return NSERROR_OK;
'@
        $OldInvalidateReturn = $OldInvalidateReturn -replace "`r`n", "`n"
        $NewInvalidateReturn = @'

	monkey_window_request_redraw(gw);
	return NSERROR_OK;
'@
        $NewInvalidateReturn = $NewInvalidateReturn -replace "`r`n", "`n"
        $InvalidateNeedle = 'moutf(MOUT_WINDOW, "INVALIDATE_AREA WIN %u ALL", gw->win_num);'
        $InvalidatePos = $BrowserText.IndexOf($InvalidateNeedle)
        if ($InvalidatePos -lt 0) {
            throw "Could not patch NetSurf monkey browser invalidate redraw."
        }
        $ReturnPos = $BrowserText.IndexOf($OldInvalidateReturn, $InvalidatePos)
        if ($ReturnPos -lt 0) {
            throw "Could not patch NetSurf monkey browser invalidate return."
        }
        $BrowserText = $BrowserText.Remove($ReturnPos, $OldInvalidateReturn.Length).
            Insert($ReturnPos, $NewInvalidateReturn)
    }
    if ($BrowserText -notmatch 'gw->in_redraw = 1;') {
        $OldRedrawStart = @'
	NSLOG(netsurf, INFO, "Issue redraw");
	moutf(MOUT_WINDOW, "REDRAW WIN %u START", gw->win_num);
#ifdef WITH_LEONOS_FETCHER
'@
        $OldRedrawStart = $OldRedrawStart -replace "`r`n", "`n"
        $NewRedrawStart = @'
	NSLOG(netsurf, INFO, "Issue redraw");
	moutf(MOUT_WINDOW, "REDRAW WIN %u START", gw->win_num);
#ifdef WITH_LEONOS_FETCHER
	gw->in_redraw = 1;
	gw->redraw_again = 0;
'@
        $NewRedrawStart = $NewRedrawStart -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldRedrawStart)) {
            throw "Could not patch NetSurf monkey browser redraw start."
        }
        $BrowserText = $BrowserText.Replace($OldRedrawStart, $NewRedrawStart)
    }
    if ($BrowserText -notmatch 'if \(gw->redraw_again\)') {
        $OldRedrawEnd = @'
#ifdef WITH_LEONOS_FETCHER
	leonos_fb_present();
#endif
'@
        $OldRedrawEnd = $OldRedrawEnd -replace "`r`n", "`n"
        $NewRedrawEnd = @'
#ifdef WITH_LEONOS_FETCHER
	gw->in_redraw = 0;
	leonos_fb_present();
	if (gw->redraw_again) {
		gw->redraw_again = 0;
		monkey_window_request_redraw(gw);
	}
#endif
'@
        $NewRedrawEnd = $NewRedrawEnd -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldRedrawEnd)) {
            throw "Could not patch NetSurf monkey browser redraw end."
        }
        $BrowserText = $BrowserText.Replace($OldRedrawEnd, $NewRedrawEnd)
    }
    if ($BrowserText -notmatch 'STATIC JS OFF') {
        $OldUrlBlock = @'
		const char *url_text = gw->current_url[0] != 0 ?
			gw->current_url : "about:blank";
'@
        $OldUrlBlock = $OldUrlBlock -replace "`r`n", "`n"
        $NewUrlBlock = @'
		const char *url_text = gw->current_url[0] != 0 ?
			gw->current_url : "about:blank";
		const char *js_label = nsoption_bool(enable_javascript) ?
			"JS EXPERIMENTAL" : "STATIC JS OFF";
'@
        $NewUrlBlock = $NewUrlBlock -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldUrlBlock)) {
            throw "Could not patch NetSurf monkey browser JavaScript label state."
        }
        $BrowserText = $BrowserText.Replace($OldUrlBlock, $NewUrlBlock)

        $OldLabel = @'
		leonos_fb_text(fb.width > 320u ? fb.width - 304u : 48u, 84,
			       "JS ENABLED", 0x000F7B47u);
'@
        $OldLabel = $OldLabel -replace "`r`n", "`n"
        $NewLabel = @'
		leonos_fb_text(fb.width > 320u ? fb.width - 304u : 48u, 84,
			       js_label, nsoption_bool(enable_javascript) ?
			       0x00A15C00u : 0x00506472u);
'@
        $NewLabel = $NewLabel -replace "`r`n", "`n"
        if (-not $BrowserText.Contains($OldLabel)) {
            throw "Could not patch NetSurf monkey browser JavaScript label."
        }
        $BrowserText = $BrowserText.Replace($OldLabel, $NewLabel)
    }
    [System.IO.File]::WriteAllText($BrowserSource, $BrowserText, [System.Text.Encoding]::ASCII)
}

function ConvertTo-NetSurfSources {
    param(
        [string] $NetSurfRoot,
        [string[]] $RelativePaths
    )

    $Sources = [System.Collections.Generic.List[string]]::new()
    foreach ($RelativePath in $RelativePaths) {
        $Source = Join-Path $NetSurfRoot ($RelativePath -replace '/', '\')
        if (-not (Test-Path -LiteralPath $Source)) {
            throw "NetSurf browser source missing at $Source."
        }
        [void] $Sources.Add($Source)
    }
    return @($Sources)
}

function Get-LeonOsNetSurfMonkeyConfig {
    $NetSurfRoot = Join-Path $VendorPath "netsurf"
    if (-not (Test-Path -LiteralPath $NetSurfRoot)) {
        throw "NetSurf source missing at $NetSurfRoot. Run ports\netsurf\fetch-netsurf.ps1 first."
    }

    $GeneratedRoot = Join-Path $Out "netsurf-generated"
    if ($UseQuickJsCore) {
        & (Join-Path $Root "ports\quickjs\fetch-quickjs.ps1") -Version $QuickJsVersion | Write-Host
        if (-not (Test-Path -LiteralPath $QuickJsSource)) {
            throw "QuickJS source missing at $QuickJsSource."
        }
    }
    $JavascriptSources = if ($NoJavaScript) {
        @(
            "content/handlers/javascript/none/none.c"
        )
    } elseif ($UseQuickJsCore) {
        @(
            "content/handlers/javascript/content.c"
        )
    } else {
        @(
            "content/handlers/javascript/content.c",
            "content/handlers/javascript/duktape/dukky.c",
            "content/handlers/javascript/duktape/duktape.c"
        )
    }
    $RelativeSources = @(
        "content/content.c",
        "content/content_factory.c",
        "content/fetch.c",
        "content/hlcache.c",
        "content/llcache.c",
        "content/mimesniff.c",
        "content/textsearch.c",
        "content/urldb.c",
        "content/no_backing_store.c",
        "content/fetchers/data.c",
        "content/fetchers/resource.c",
        "content/fetchers/about/about.c",
        "content/fetchers/about/blank.c",
        "content/fetchers/about/certificate.c",
        "content/fetchers/about/chart.c",
        "content/fetchers/about/choices.c",
        "content/fetchers/about/config.c",
        "content/fetchers/about/imagecache.c",
        "content/fetchers/about/nscolours.c",
        "content/fetchers/about/query.c",
        "content/fetchers/about/query_auth.c",
        "content/fetchers/about/query_fetcherror.c",
        "content/fetchers/about/query_privacy.c",
        "content/fetchers/about/query_timeout.c",
        "content/fetchers/about/testament.c",
        "content/fetchers/about/websearch.c",
        "content/fetchers/file/dirlist.c",
        "content/fetchers/file/file.c",
        "content/handlers/css/css.c",
        "content/handlers/css/dump.c",
        "content/handlers/css/internal.c",
        "content/handlers/css/hints.c",
        "content/handlers/css/select.c"
    ) + $JavascriptSources + @(
        "content/handlers/javascript/fetcher.c",
        "content/handlers/html/box_construct.c",
        "content/handlers/html/box_inspect.c",
        "content/handlers/html/box_manipulate.c",
        "content/handlers/html/box_normalise.c",
        "content/handlers/html/box_special.c",
        "content/handlers/html/box_textarea.c",
        "content/handlers/html/css.c",
        "content/handlers/html/css_fetcher.c",
        "content/handlers/html/dom_event.c",
        "content/handlers/html/font.c",
        "content/handlers/html/form.c",
        "content/handlers/html/forms.c",
        "content/handlers/html/html.c",
        "content/handlers/html/imagemap.c",
        "content/handlers/html/interaction.c",
        "content/handlers/html/layout.c",
        "content/handlers/html/layout_flex.c",
        "content/handlers/html/object.c",
        "content/handlers/html/redraw.c",
        "content/handlers/html/redraw_border.c",
        "content/handlers/html/script.c",
        "content/handlers/html/table.c",
        "content/handlers/html/textselection.c",
        "content/handlers/text/textplain.c",
        "content/handlers/image/image.c",
        "content/handlers/image/image_cache.c",
        "content/handlers/image/bmp.c",
        "content/handlers/image/gif.c",
        "content/handlers/image/ico.c",
        "../../leonos_libc/src/leonos_fetch.c",
        "../../leonos_libc/src/netsurf_stubs.c",
        "utils/bloom.c",
        "utils/corestrings.c",
        "utils/file.c",
        "utils/filepath.c",
        "utils/hashmap.c",
        "utils/hashtable.c",
        "utils/idna.c",
        "utils/libdom.c",
        "utils/log.c",
        "utils/messages.c",
        "utils/nscolour.c",
        "utils/nsoption.c",
        "utils/punycode.c",
        "utils/ssl_certs.c",
        "utils/talloc.c",
        "utils/time.c",
        "utils/url.c",
        "utils/useragent.c",
        "utils/utf8.c",
        "utils/utils.c",
        "utils/http/challenge.c",
        "utils/http/generics.c",
        "utils/http/primitives.c",
        "utils/http/parameter.c",
        "utils/http/cache-control.c",
        "utils/http/content-disposition.c",
        "utils/http/content-type.c",
        "utils/http/strict-transport-security.c",
        "utils/http/www-authenticate.c",
        "utils/nsurl/nsurl.c",
        "utils/nsurl/parse.c",
        "desktop/cookie_manager.c",
        "desktop/knockout.c",
        "desktop/hotlist.c",
        "desktop/mouse.c",
        "desktop/plot_style.c",
        "desktop/print.c",
        "desktop/search.c",
        "desktop/searchweb.c",
        "desktop/scrollbar.c",
        "desktop/textarea.c",
        "desktop/version.c",
        "desktop/system_colour.c",
        "desktop/local_history.c",
        "desktop/global_history.c",
        "desktop/treeview.c",
        "desktop/page-info.c",
        "desktop/bitmap.c",
        "desktop/browser.c",
        "desktop/browser_window.c",
        "desktop/browser_history.c",
        "desktop/download.c",
        "desktop/frames.c",
        "desktop/netsurf.c",
        "desktop/cw_helper.c",
        "desktop/save_complete.c",
        "desktop/save_text.c",
        "desktop/selection.c",
        "desktop/textinput.c",
        "desktop/gui_factory.c",
        "frontends/monkey/main.c",
        "frontends/monkey/output.c",
        "frontends/monkey/filetype.c",
        "frontends/monkey/schedule.c",
        "frontends/monkey/bitmap.c",
        "frontends/monkey/plot.c",
        "frontends/monkey/browser.c",
        "frontends/monkey/download.c",
        "frontends/monkey/401login.c",
        "frontends/monkey/layout.c",
        "frontends/monkey/dispatch.c",
        "frontends/monkey/fetch.c"
    )

    $Sources = @(ConvertTo-NetSurfSources -NetSurfRoot $NetSurfRoot -RelativePaths $RelativeSources)
    $Sources += $LeoStbImageSrc
    if ($UseQuickJsCore) {
        $Sources += $QuickJsBackendSrc
        $Sources += @(
            (Join-Path $QuickJsSource "quickjs.c"),
            (Join-Path $QuickJsSource "dtoa.c"),
            (Join-Path $QuickJsSource "libregexp.c"),
            (Join-Path $QuickJsSource "libunicode.c"),
            (Join-Path $QuickJsSource "cutils.c")
        )
    } elseif (-not $NoJavaScript) {
        $DuktapeGeneratedDir = Join-Path $GeneratedRoot "duktape"
        if (-not (Test-Path -LiteralPath $DuktapeGeneratedDir)) {
            throw "Duktape generated source directory missing at $DuktapeGeneratedDir."
        }
        $Sources += @(Get-ChildItem -LiteralPath $DuktapeGeneratedDir -Filter "*.c" -File |
            Sort-Object Name |
            Select-Object -ExpandProperty FullName)
    }

    return [pscustomobject] @{
        Name = "netsurf-monkey"
        Repo = $Root
        Sources = $Sources
        Includes = @(
            $Src32Include,
            $GeneratedRoot,
            $NetSurfRoot,
            (Join-Path $NetSurfRoot "include"),
            (Join-Path $NetSurfRoot "content\handlers"),
            (Join-Path $NetSurfRoot "frontends"),
            (Join-Path $NetSurfRoot "frontends\monkey"),
            (Join-Path $VendorPath "libcss\include"),
            (Join-Path $VendorPath "libdom\include"),
            (Join-Path $VendorPath "libhubbub\include"),
            (Join-Path $VendorPath "libparserutils\include"),
            (Join-Path $VendorPath "libwapcaplet\include"),
            (Join-Path $VendorPath "libnsbmp\include"),
            (Join-Path $VendorPath "libnsgif\include"),
            (Join-Path $VendorPath "libsvgtiny\include"),
            (Join-Path $VendorPath "libnsutils\include"),
            (Join-Path $VendorPath "stb"),
            $QuickJsSource
        )
        Defines = @(
            "monkey",
            "nsmonkey",
            "__riscos__",
            "NETSURF_HOMEPAGE=\""about:blank\""",
            "NETSURF_UA_FORMAT_STRING=\""LeonOS-NetSurf/%d.%d\""",
            "NETSURF_BUILTIN_LOG_FILTER=\""\""",
            "NETSURF_BUILTIN_VERBOSE_FILTER=\""\""",
            "MONKEY_RESPATH=\""/netsurf\""",
            "_GNU_SOURCE",
            "_DEFAULT_SOURCE",
            "_POSIX_C_SOURCE=200809L",
            "LEONOS_USER_APP",
            "WITH_LEONOS_FETCHER",
            "WITH_LEONOS_STB_IMAGE",
            "WITH_BMP",
            "WITH_GIF"
        ) + $(if ($UseQuickJsCore) {
            @(
                "LEONOS_NETSURF_QUICKJS_CORE",
                "LEONOS_QUICKJS_NO_ATOMICS",
                "LEONOS_QUICKJS_NO_STACK_CHECK",
                "LEONOS_QUICKJS_NO_MALLOC_USABLE_SIZE",
                "alloca=__builtin_alloca",
                "CONFIG_VERSION=\`"$QuickJsVersion\`"",
                "_GNU_SOURCE"
            )
        } elseif ($NoJavaScript) { @() } else {
            @(
                "DUK_OPT_HAVE_CUSTOM_H"
            )
        })
    }
}

function Get-LeonOsProbeLib {
    param([string] $Name)

    if ($Name -eq "netsurf-monkey") {
        return Get-LeonOsNetSurfMonkeyConfig
    }

    $Repo = Join-Path $VendorPath $Name
    $Src = Join-Path $Repo "src"
    $Inc = Join-Path $Repo "include"
    if (-not (Test-Path -LiteralPath $Src)) {
        throw "$Name source missing at $Src. Run ports\netsurf\fetch-netsurf.ps1 first."
    }

    switch ($Name) {
        "libwapcaplet" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
                Includes = @($Inc, $Src)
            }
        }
        "libparserutils" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
                Includes = @($Inc, $Src)
                Defines = @("WITHOUT_ICONV_FILTER")
            }
        }
        "libhubbub" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File |
                    Where-Object { $_.Name -ne "autogenerated-element-type.c" } |
                    Select-Object -ExpandProperty FullName)
                Includes = @(
                    $Inc,
                    $Src,
                    (Join-Path $VendorPath "libparserutils\include"),
                    (Join-Path $VendorPath "libwapcaplet\include")
                )
            }
        }
        "libcss" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File |
                    Where-Object { $_.Name -ne "css_property_parser_gen.c" } |
                    Select-Object -ExpandProperty FullName)
                Includes = @(
                    $Inc,
                    $Src,
                    (Join-Path $VendorPath "libparserutils\include"),
                    (Join-Path $VendorPath "libwapcaplet\include")
                )
            }
        }
        "libdom" {
            $DomSources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
            $DomSources += (Join-Path $Repo "bindings\hubbub\parser.c")
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = $DomSources
                Includes = @(
                    $Inc,
                    $Src,
                    (Join-Path $Repo "bindings\hubbub"),
                    (Join-Path $VendorPath "libparserutils\include"),
                    (Join-Path $VendorPath "libhubbub\include"),
                    (Join-Path $VendorPath "libwapcaplet\include")
                )
            }
        }
        "libnsbmp" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
                Includes = @($Inc, $Src)
            }
        }
        "libnsgif" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
                Includes = @($Inc, $Src)
            }
        }
        "libsvgtiny" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File |
                    Where-Object { $_.Name -ne "autogenerated_colors.c" } |
                    Select-Object -ExpandProperty FullName)
                Includes = @(
                    $Inc,
                    $Src,
                    (Join-Path $VendorPath "libdom\include"),
                    (Join-Path $VendorPath "libhubbub\include"),
                    (Join-Path $VendorPath "libparserutils\include"),
                    (Join-Path $VendorPath "libwapcaplet\include")
                )
            }
        }
        "libnsutils" {
            return [pscustomobject] @{
                Name = $Name
                Repo = $Repo
                Sources = @(Get-ChildItem -LiteralPath $Src -Recurse -Filter "*.c" -File | Select-Object -ExpandProperty FullName)
                Includes = @($Inc, $Src)
                Defines = @("_GNU_SOURCE", "_DEFAULT_SOURCE", "_POSIX_C_SOURCE=200809L")
            }
        }
        default {
            throw "Unknown NetSurf probe library '$Name'."
        }
    }
}

function Invoke-LeonOsCompile {
    param(
        [string] $Source,
        [string] $Object,
        [string[]] $Includes,
        [string[]] $Defines = @()
    )

    $Args = @()
    if ($Toolchain.Kind -eq "clang-lld") {
        $Args += "--target=i686-elf"
    }
    $Args += @(
        "-std=c99",
        "-Os",
        "-ffreestanding",
        "-fno-builtin",
        "-fno-stack-protector",
        "-m32",
        "-mno-sse",
        "-mno-mmx",
        "-nostdinc",
        "-isystem", $LibcInc
    )
    $Args += "-D_ALIGNED=__attribute__((aligned))"
    $Args += "-DSTMTEXPR=1"
    foreach ($Define in $Defines) {
        $Args += "-D$Define"
    }
    foreach ($Include in $Includes) {
        $Args += @("-I", $Include)
    }
    $Args += @("-c", $Source, "-o", $Object)

    & $Toolchain.Cc @Args
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to compile $Source for LeonOS NetSurf probe."
    }
}

$Objects = [System.Collections.Generic.List[string]]::new()
if ($Libraries -contains "libparserutils") {
    Ensure-LibParserUtilsGeneratedFiles
}
if ($Libraries -contains "libhubbub") {
    Ensure-HubbubGeneratedFiles
}
if (($Libraries -contains "libdom") -or ($Libraries -contains "libsvgtiny")) {
    Ensure-LibDomInstalledHeaders
}
if ($Libraries -contains "libsvgtiny") {
    Ensure-LibSvgTinyGeneratedFiles
}
if ($Libraries -contains "libcss") {
    Ensure-LibCssGeneratedFiles
}
if ($Libraries -contains "netsurf-monkey") {
    Ensure-NetSurfLeonOsSourcePatches
    Ensure-NetSurfGeneratedFiles
    if ((-not $NoJavaScript) -and (-not $UseQuickJsCore)) {
        Ensure-NetSurfDuktapeGeneratedFiles
    }
}

$LibcOut = Join-Path $Out "leonos_libc"
New-Item -ItemType Directory -Path $LibcOut -Force | Out-Null
Invoke-LeonOsCompile -Source $LibcSrc -Object (Join-Path $LibcOut "leostd.o") `
    -Includes @($Out)
[void] $Objects.Add((Join-Path $LibcOut "leostd.o"))
$SetjmpObj = Join-Path $LibcOut "setjmp-i386.o"
& $Nasm "-f" "elf32" $LibcSetjmpSrc "-o" $SetjmpObj
if ($LASTEXITCODE -ne 0) {
    throw "NASM failed while assembling the LeonOS libc setjmp/longjmp object."
}
[void] $Objects.Add($SetjmpObj)

foreach ($Library in $Libraries) {
    $Config = Get-LeonOsProbeLib $Library
    $LibOut = Join-Path $Out $Config.Name
    New-Item -ItemType Directory -Path $LibOut -Force | Out-Null
    $Compiled = 0
    foreach ($Source in $Config.Sources) {
        $Relative = $Source.Substring($Config.Repo.Length).TrimStart('\', '/')
        $ObjectName = ($Relative -replace '[\\/:]', '_') -replace '\.c$', '.o'
        $Object = Join-Path $LibOut $ObjectName
        $Defines = @()
        if ($Config.PSObject.Properties.Match("Defines").Count -gt 0) {
            $Defines = @($Config.Defines)
        }
        Invoke-LeonOsCompile -Source $Source -Object $Object -Includes $Config.Includes -Defines $Defines
        [void] $Objects.Add($Object)
        $Compiled += 1
    }
    Write-Host ("LeonOS NetSurf probe: compiled {0} objects for {1}" -f $Compiled, $Config.Name)
}

$Manifest = Join-Path $Out "objects.txt"
[System.IO.File]::WriteAllLines($Manifest, $Objects)
Write-Host ("LeonOS NetSurf probe: compiled {0} total objects to {1}" -f $Objects.Count, $Out)

if ($Libraries -contains "netsurf-monkey") {
    $LinkedObjects = @($Objects | Where-Object { $_ -notmatch '[\\/]libsvgtiny[\\/]' })
    $LinkRsp = Join-Path $Out "objects-no-svg.rsp"
    $LinkRspLines = @($LinkedObjects | ForEach-Object { '"' + $_ + '"' })
    [System.IO.File]::WriteAllLines($LinkRsp, $LinkRspLines, [System.Text.Encoding]::ASCII)

    $LinkedElf = Join-Path $Out "netsurf-monkey.elf"
    & $Toolchain.Ld "-m" "elf_i386" "-e" "main" "@$LinkRsp" "-o" $LinkedElf
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $LinkedElf)) {
        throw "Failed to link LeonOS NetSurf monkey probe executable."
    }
    Write-Host ("LeonOS NetSurf probe: linked {0} browser objects to {1}" -f $LinkedObjects.Count, $LinkedElf)

    $LeoOut = Join-Path $Out "leo1"
    New-Item -ItemType Directory -Path $LeoOut -Force | Out-Null
    $LeoCrtObj = Join-Path $LeoOut "crt0.o"
    $LeoLibcObj = Join-Path $LeoOut "leostd-user.o"
    $LeoSetjmpObj = Join-Path $LeoOut "setjmp-i386.o"
    $LeoFetchObj = Join-Path $LeoOut "leonos-fetch-user.o"
    $LeoMainObj = Join-Path $LeoOut "netsurf-leo1-main.o"
    $LeoElf = Join-Path $Out "NETSURF.elf"
    $LeoBin = Join-Path $Out "NETSURF.LEO"

    & $Nasm "-f" "elf32" (Join-Path $Root "src32\user\crt0.asm") "-o" $LeoCrtObj
    if ($LASTEXITCODE -ne 0) {
        throw "NASM failed while assembling the NetSurf LEO1 crt0."
    }

    Invoke-LeonOsCompile -Source $LibcSrc -Object $LeoLibcObj `
        -Includes @($Src32Include, $Out) -Defines @("LEONOS_USER_APP")
    & $Nasm "-f" "elf32" $LibcSetjmpSrc "-o" $LeoSetjmpObj
    if ($LASTEXITCODE -ne 0) {
        throw "NASM failed while assembling the NetSurf LEO1 setjmp/longjmp object."
    }
    $LeoNetSurfRoot = Join-Path $VendorPath "netsurf"
    $LeoGeneratedRoot = Join-Path $Out "netsurf-generated"
    Invoke-LeonOsCompile -Source $LeoFetchSrc -Object $LeoFetchObj `
        -Includes @(
            $Src32Include,
            $LeoGeneratedRoot,
            $LeoNetSurfRoot,
            (Join-Path $LeoNetSurfRoot "include"),
            (Join-Path $LeoNetSurfRoot "content\handlers"),
            (Join-Path $LeoNetSurfRoot "frontends"),
            (Join-Path $VendorPath "libwapcaplet\include")
        ) -Defines @("LEONOS_USER_APP")
    Invoke-LeonOsCompile -Source $Leo1MainSrc -Object $LeoMainObj `
        -Includes @($Src32Include, $Out) -Defines @("LEONOS_USER_APP")

    $LeoBrowserObjects = @($LinkedObjects | Where-Object {
        $_ -notmatch '[\\/]leonos_libc[\\/]leostd\.o$' -and
        $_ -notmatch '[\\/]leonos_libc[\\/]setjmp-i386\.o$' -and
        $_ -notmatch 'leonos_fetch\.o$'
    })
    $LeoObjects = @($LeoCrtObj, $LeoMainObj, $LeoLibcObj, $LeoSetjmpObj, $LeoFetchObj) +
        $LeoBrowserObjects
    $LeoRsp = Join-Path $Out "leo1-objects.rsp"
    [System.IO.File]::WriteAllLines(
        $LeoRsp,
        @($LeoObjects | ForEach-Object { '"' + $_ + '"' }),
        [System.Text.Encoding]::ASCII)

    & $Toolchain.Ld "-m" "elf_i386" "-T" (Join-Path $Root "src32\user\leonos_user.ld") `
        "-nostdlib" "-Map" (Join-Path $Out "NETSURF.link.map") `
        "-o" $LeoElf "@$LeoRsp"
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $LeoElf)) {
        throw "Failed to link NetSurf as a LeonOS LEO1 user app."
    }

    & $Toolchain.Objcopy "-O" "binary" $LeoElf $LeoBin
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $LeoBin)) {
        throw "objcopy failed while producing NETSURF.LEO."
    }
    $LeoBytes = Sync-Leo1ImageSize ([System.IO.File]::ReadAllBytes($LeoBin))
    [System.IO.File]::WriteAllBytes($LeoBin, $LeoBytes)
    if ($LeoBytes.Length -lt 32 -or
        $LeoBytes[0] -ne 0x4C -or $LeoBytes[1] -ne 0x45 -or
        $LeoBytes[2] -ne 0x4F -or $LeoBytes[3] -ne 0x31) {
        throw "NETSURF.LEO is missing the LEO1 header."
    }
    if ($LeoBytes[4] -ne 0x02) {
        throw "NETSURF.LEO must declare LEO1 ABI version 2."
    }
    Write-Host ("LeonOS NetSurf probe: linked real LEO1 smoke app {0} ({1} bytes)" -f $LeoBin, $LeoBytes.Length)
}
